#%RAML 1.0
#baseUri: https://mocksvc.mulesoft.com/mocks/e0bcf131-b12c-472c-bcb9-4fb68c1fed3c
baseUri: http://192.168.0.144:8080
title: Robot Telepresence
version: v1
mediaType: application/json
uses: 
  r: robot-resources.raml
  t: robot-types.raml

/motionTargets:
  /head:
    type: 
      r.motionTarget: { target-type: t.head-motion-target }
  /left-shoulder:
    type: 
      r.motionTarget: { target-type: t.left-shoulder-motion-target }
  /right-shoulder:
    type: 
      r.motionTarget: { target-type: t.right-shoulder-motion-target }
  /left-elbow:
    type: 
      r.motionTarget: { target-type: t.left-elbow-motion-target }
  /right-elbow:
    type: 
      r.motionTarget: { target-type: t.right-elbow-motion-target }
/behaviors:
  /walks:
    type: 
      r.behavior: { behavior-type: t.walk }
    /current:
      type: 
        r.current-behavior: { behavior-type: t.walk }
  /talks:
    type: 
      r.behavior: { behavior-type: t.talk }
    /current:
      type: 
        r.current-behavior: { behavior-type: t.talk }
  /kicks:
    type: 
      r.behavior: { behavior-type: t.kick }
    /current:
      type: 
        r.current-behavior: { behavior-type: t.kick }
  /postures:
    type: 
      r.behavior: { behavior-type: t.posture }
    /current:
      type: 
        r.current-behavior: { behavior-type: t.posture }
  /awakes:
    type: 
      r.behavior: { behavior-type: t.awake }
    /current:
      type: 
        r.current-behavior: { behavior-type: t.awake }
